defaults:
  - _self_

batch_size: 64
canvas_size: 64
cpu: false
data_path: ../data
experiment_name: ${now:%Y-%m-%d_%H-%M-%S}
learning_rate: 0.01
log_interval: 100
loss_ema_decay: 0.999
mixed_precision: 'no'
num_workers: 4
pin_memory: true
seed: 42
steps: 100_000
warmup_percentage: 0.1

hydra:
  run:
    dir: ${oc.env:EXPERIMENT_ROOT}/${hydra.job.name}/${experiment_name}
  sweep:
    dir: ${oc.env:EXPERIMENT_ROOT}/multirun
    subdir: ${experiment_name}